### ISSUE TITLE
How to use for plain text?

### ISSUE THREAD

**Issue by panathos** [absop/RainbowBrackets#4]
Here is my RainbowBrackets.sublime-settings.
Files with extension ".cmd" are working ok, but no rainbow colors in .txt files. 
How use this plugin for ascii files? 

{
	"languages": {
		"plaintext": {
			"extensions": ["txt"],
			"mode":"all"
		},
         "dosbatch": {
	    	"extensions": ["cmd"],
	    	"mode": "all",
	    }
	}
}

**Comment by absop** [comment]
Currently, this plugin is not work well in plain text. A proper sublime-syntax file is need, which is used by sublime to extract tokens.  You can load the plugin in plain text views or other arbitrarily views forcibly, with using the command `RainbowBrackets make rainbow`(see the last version), But it may not work well because of wrong tokens.

**Comment by absop** [comment]
> Here is my RainbowBrackets.sublime-settings.
> Files with extension ".cmd" are working ok, but no rainbow colors in .txt files.
> How use this plugin for ascii files?
> 
> {
> "languages": {
> "plaintext": {
> "extensions": ["txt"],
> "mode":"all"
> },
> "dosbatch": {
> "extensions": ["cmd"],
> "mode": "all",
> }
> }
> }

I have update the plugin, now you can use the command `RB make rainbow` to add colors for brackets in current file.

**Comment by panathos** [comment]
Well done! Work like a charm 👍
